#!/bin/bash

elmo_repository="elmo"
elmo_source="https://github.com/sca-research/ELMO.git"

if [ -d ${elmo_repository} ]; then
    echo "ELMO tool already installed."
else
    echo "ELMO tool NOT installed... Installing via online resources..."
    # Download the tool
    git clone --depth=1 --branch=master ${elmo_source} ${elmo_repository}
    rm -rf ./${elmo_repository}/.git

    # Compile the tool
    cd ./${elmo_repository}
    make
    cd ..
fi
